version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - run:
          name: Build for production
          command: npm run prod
      - run:
          name: Use build folder to deploy
          command: |
            rm -v !("build"|".git")
            cd build
            mv * ..
            cd ..
            rm build
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  build-and-deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires: build