version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/php:7.2-node-browsers
    steps:
      - checkout
      - run:
          name: Build for production
          command: |
            npm install
            cd react
            npm install
            cd ..
            npm run prod
      - run:
          name: Deploy the build folder
          command: |
            mkdir deploy
            cd deploy
            git config --global user.email "jason.lipowicz@gmail.com"
            git config --global user.name "Jason Lipowicz"
            git init
            git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
            git pull heroku master
            cd ../build
            mv ../deploy/.git .
            git add .
            git commit -m "Deploy to Heroku"
            git push heroku master
workflows:
  build-and-deploy:
    jobs:
      - deploy